---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-lodging
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/mtn/data'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lodging-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
